# Generated by Django 5.1.2 on 2024-10-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='main_image',
            field=models.BooleanField(blank=True),
        ),
    ]
